/**
 * Build script that embeds frontend assets using Bun's native file embedding.
 *
 * This script:
 * 1. Builds the frontend with Vite
 * 2. Scans .vite-build/ for all output files
 * 3. Generates src/generated/embedded-assets.ts with `import ... with { type: "file" }` statements
 *
 * When compiled with `bun build --compile`, these imports are embedded directly into the binary.
 * No base64 encoding overhead - files are stored as raw bytes.
 */

import { $ } from "bun";
import { join } from "node:path";

const rootDir = join(import.meta.dir, "..");
const viteBuildDir = join(rootDir, ".vite-build");
const outputFile = join(rootDir, "src", "generated", "embedded-assets.ts");

async function main() {
  console.log("Building frontend with Vite...");
  const result = await $`bunx vite build`.cwd(rootDir).nothrow();

  if (result.exitCode !== 0) {
    console.error("Vite build failed:");
    console.error(result.stderr.toString());
    process.exit(1);
  }

  console.log("Scanning built files...");
  const files = await Array.fromAsync(
    new Bun.Glob("**/*").scan({ cwd: viteBuildDir, dot: false })
  );

  // Filter to actual files (not directories)
  const assetFiles: string[] = [];
  for (const file of files) {
    const fullPath = join(viteBuildDir, file);
    const bunFile = Bun.file(fullPath);
    if ((await bunFile.exists()) && bunFile.size > 0) {
      assetFiles.push(file);
    }
  }

  if (assetFiles.length === 0) {
    console.error("No files found in .vite-build/ - build may have failed");
    process.exit(1);
  }

  console.log(`Found ${assetFiles.length} files to embed`);

  // Generate import statements with unique identifiers
  const imports: string[] = [];
  const mappings: string[] = [];

  for (let i = 0; i < assetFiles.length; i++) {
    const file = assetFiles[i];
    // Use index to guarantee unique identifiers (avoids collision from similar paths)
    const identifier = `_asset${i}`;
    const urlPath = "/" + file;
    const importPath = `../../.vite-build/${file}`;

    imports.push(
      `import ${identifier} from "${importPath}" with { type: "file" };`
    );
    mappings.push(`  "${urlPath}": ${identifier} as string,`);

    console.log(`  ${urlPath}`);
  }

  const output = `// Auto-generated by scripts/embed-assets.ts - do not edit
${imports.join("\n")}

export const assets: Record<string, string> = {
${mappings.join("\n")}
};
`;

  await Bun.write(outputFile, output);
  console.log(`\nGenerated ${outputFile}`);
}

main().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
